/*obras*/
const obras = [
    {
      id: "1",
      titulo: "Colores",
      img: "https://marianspace.github.io/Tugaleria/img/1.jpg",
      artista: "Mariana",
      tecnica: "Bordado",
      ano: 2020,
      precio: 5000,
      detalle: "obras/1.html",
      stock: 1,
    },
    {
      id: "2",
      titulo: "Esto no es una pipa",
      img: "https://marianspace.github.io/Tugaleria/img/2.jpg",
      artista: "Pepita",
      tecnica: "Bordado sobre papel",
      ano: 2023,
      precio: 4400,
      detalle: "obras/2.html",
      stock: 1,
    },
    {
      id: "3",
      titulo: "Familia",
      img: "https://marianspace.github.io/Tugaleria/img/3.jpg",
      artista: "Mariana",
      tecnica: "Bordado sobre fotografía",
      ano: 2023,
      precio: 5000,
      detalle: "obras/3.html",
      stock: 1,
    },
    {
      id: "4",
      titulo: "Una Mano",
      artista: "Constanza",
      img: "https://marianspace.github.io/Tugaleria/img/4.jpg",
      tecnica: "Bordado sobre fotografía",
      ano: 2023,
      precio: 5000,
      detalle: "obras/4.html",
      stock: 1,
    }
  ];